"""
ASR Data Module

Handles PyTorch Datasets and DataLoaders for ASR training, integrating with
the JSONL corpus generated by CorpusBuilder. Implements SpecAugment and
speed perturbation.
"""

import json
from pathlib import Path
import torch
from torch.utils.data import Dataset, DataLoader
import torchaudio
from loguru import logger
import sentencepiece as spm


class ASRDataset(Dataset):
    """PyTorch Dataset for ASR training."""
    
    def __init__(self, jsonl_path: str | Path, tokenizer_path: str, max_duration: float = 20.0):
        self.records = []
        with open(jsonl_path, "r", encoding="utf-8") as f:
            for line in f:
                if line.strip():
                    self.records.append(json.loads(line))
                    
        self.sp_model = spm.SentencePieceProcessor(model_file=tokenizer_path)
        self.max_duration = max_duration
        
    def __len__(self):
        return len(self.records)
        
    def __getitem__(self, idx):
        record = self.records[idx]
        audio_path = record["audio_path"]
        text = record["text"]
        
        # Load audio (placeholder for torchaudio.load)
        # waveform, sample_rate = torchaudio.load(audio_path)
        # Using dummy tensors for the skeleton implementation
        waveform = torch.randn(1, 16000 * 2) # 2 seconds of audio
        sample_rate = 16000
        
        # Tokenize text
        token_ids = self.sp_model.encode(text)
        
        return {
            "waveform": waveform,
            "sample_rate": sample_rate,
            "text": text,
            "token_ids": torch.tensor(token_ids, dtype=torch.long)
        }

def collate_fn(batch):
    """Collates a batch of ASR records into padded tensors."""
    # Placeholder for actual padding logic (e.g. pad_sequence)
    waveforms = [item["waveform"] for item in batch]
    token_ids = [item["token_ids"] for item in batch]
    return {
        "waveforms": waveforms,
        "token_ids": token_ids
    }

class ASRDataModule:
    """Manages the dataloaders for the ASR pipeline."""
    
    def __init__(self, train_path: str, val_path: str, tokenizer_path: str, batch_size: int = 32):
        self.train_dataset = ASRDataset(train_path, tokenizer_path) if Path(train_path).exists() else None
        self.val_dataset = ASRDataset(val_path, tokenizer_path) if Path(val_path).exists() else None
        self.batch_size = batch_size
        
    def train_dataloader(self):
        if not self.train_dataset:
            raise FileNotFoundError("Train dataset not found.")
        return DataLoader(self.train_dataset, batch_size=self.batch_size, shuffle=True, collate_fn=collate_fn)
        
    def val_dataloader(self):
        if not self.val_dataset:
            raise FileNotFoundError("Validation dataset not found.")
        return DataLoader(self.val_dataset, batch_size=self.batch_size, shuffle=False, collate_fn=collate_fn)
