"""
SentencePiece BPE Trainer

Trains the Byte-Pair Encoding (BPE) subword tokenizers required for the ASR and MT models.
The architecture specification explicitly mandates disjoint vocabularies for source and target
languages to avoid representation collapse when handling highly divergent scripts or normalized dialects.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

import sentencepiece as spm
from loguru import logger
import yaml


class BPETrainer:
    """
    Wrapper around the SentencePiece processor for training dialect-aware tokenizers.
    Reads normalized text from the JSONL corpus files generated by CorpusBuilder.
    """

    def __init__(self, config_path: str = "config/tokenizer.yaml"):
        self.config_path = Path(config_path)
        with open(self.config_path, "r") as f:
            cfg = yaml.safe_load(f)
        self.config = cfg.get("tokenizer", {})
        logger.info(f"BPETrainer initialized with config: {self.config}")

    def prepare_text_file(self, corpus_path: str | Path, output_text_path: str | Path) -> None:
        """
        Extracts raw normalized text from a JSONL corpus file into a plain text file
        which SentencePiece requires for training.
        """
        corpus_path = Path(corpus_path)
        output_text_path = Path(output_text_path)
        output_text_path.parent.mkdir(parents=True, exist_ok=True)
        
        count = 0
        with open(corpus_path, "r", encoding="utf-8") as f_in, open(output_text_path, "w", encoding="utf-8") as f_out:
            for line in f_in:
                if not line.strip():
                    continue
                try:
                    record = json.loads(line)
                    text = record.get("text", record.get("source_text", ""))
                    if text:
                        f_out.write(text + "\n")
                        count += 1
                except json.JSONDecodeError:
                    pass
        logger.info(f"Extracted {count} lines of text to {output_text_path}")

    def train(self, input_text_path: str | Path, model_prefix: str) -> None:
        """
        Trains the SentencePiece model.
        """
        input_text_path = Path(input_text_path)
        if not input_text_path.exists():
            raise FileNotFoundError(f"Input text file not found: {input_text_path}")

        logger.info(f"Training SentencePiece BPE model '{model_prefix}' from {input_text_path}...")
        
        # Build the argument string for sentencepiece
        args = [
            f"--input={input_text_path}",
            f"--model_prefix={model_prefix}",
            f"--vocab_size={self.config.get('vocab_size', 32000)}",
            f"--character_coverage={self.config.get('character_coverage', 1.0)}",
            f"--model_type={self.config.get('model_type', 'bpe')}",
            f"--pad_id={self.config.get('pad_id', 0)}",
            f"--unk_id={self.config.get('unk_id', 1)}",
            f"--bos_id={self.config.get('bos_id', 2)}",
            f"--eos_id={self.config.get('eos_id', 3)}",
            f"--pad_piece={self.config.get('pad_piece', '<pad>')}",
            f"--unk_piece={self.config.get('unk_piece', '<unk>')}",
            f"--bos_piece={self.config.get('bos_piece', '<s>')}",
            f"--eos_piece={self.config.get('eos_piece', '</s>')}",
            f"--input_sentence_size={self.config.get('input_sentence_size', 5000000)}",
            f"--shuffle_input_sentence={'true' if self.config.get('shuffle_input_sentence', True) else 'false'}",
        ]
        
        spm.SentencePieceTrainer.train(" ".join(args))
        logger.info(f"SentencePiece training complete. Models saved as {model_prefix}.model and {model_prefix}.vocab")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Train SentencePiece BPE Tokenizer")
    parser.add_argument("--corpus", type=str, required=True, help="Path to input JSONL corpus")
    parser.add_argument("--prefix", type=str, required=True, help="Prefix for the output model files (e.g., 'models/tokenizer_asr')")
    parser.add_argument("--config", type=str, default="config/tokenizer.yaml", help="Path to tokenizer config")
    
    args = parser.parse_args()
    
    trainer = BPETrainer(config_path=args.config)
    
    # Create a temporary text file for SentencePiece
    temp_text_file = f"{args.prefix}_temp_input.txt"
    trainer.prepare_text_file(args.corpus, temp_text_file)
    trainer.train(temp_text_file, args.prefix)
    
    # Clean up the temporary file
    Path(temp_text_file).unlink(missing_ok=True)
