"""
HiFi-GAN Vocoder

Reconstructs high-fidelity audio waveforms from the mel-spectrograms
generated by FastPitch in real-time.
"""

import torch
import torch.nn as nn
from loguru import logger
import yaml
from pathlib import Path


class HiFiGANVocoder(nn.Module):
    """
    Wrapper for HiFi-GAN V1 vocoder.
    """
    
    def __init__(self, config_path: str = "config/tts.yaml"):
        super().__init__()
        self.config_path = Path(config_path)
        with open(self.config_path, "r") as f:
            cfg = yaml.safe_load(f)
        self.config = cfg.get("tts", {}).get("vocoder", {})
        
        self.sample_rate = self.config.get("sample_rate", 22050)
        
        # Skeleton implementation of Generator
        self.generator = nn.Sequential(
            nn.Conv1d(80, 512, 7, 1, padding=3),
            nn.LeakyReLU(),
            nn.ConvTranspose1d(512, 256, 16, 8, padding=4),
            nn.LeakyReLU(),
            nn.Conv1d(256, 1, 7, 1, padding=3)
        )
        
        logger.info(f"Initialized HiFiGANVocoder (SR: {self.sample_rate})")

    def forward(self, mel: torch.Tensor):
        """
        Forward pass converting mel-spectrogram to waveform.
        mel: (batch, n_mels, time)
        returns: (batch, 1, audio_samples)
        """
        waveform = self.generator(mel)
        return waveform
